export type NewsType =
  | "guarded from murder"
  | "guarded from assault"
  | "guarded from poison"
  | "fighter was assaulted"
  | "fighter died from poison"
  | "fighter murdered"
  | "fighter has gone up in strength or fitness"
  | "fighter is doped up"
  | "fighter died of overdose"
  | "fighter is sick"
  | "fighter is hallucinating"
  | "fight event next week"
  | "manager prosecuted"
  | "manager retired"
