export type TimerName =
  | "on a rampage"
  | "last combat action"
  | "memory of enemy behind"
  | "move action"
  | "persist direction"
  | "passive recover"
  | "just landed attack"
  | "just took hit"
  | "targeted for attack"
  | "just recovered"
  | "hallucinations"
  | "was just sick"
